fix: change args from let to mut for reassignment compatibility
Fixes Nu parser error:
  Error: nu::parser::assignment_requires_mutable_variable
  '' needs to be a mutable variable to support append ['--fix']
  Use 'mut args' instead of 'let args'